const {chromium,webkit,devices}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await (process.env.ENGINE==='webkit'?webkit:chromium).launch({headless:true,downloadsPath:'/home/jeremy/SetterStats-test-artifacts',...(process.env.ENGINE==='webkit'?{}:{executablePath:process.env.CHROME_PATH||'/snap/bin/chromium'})});
 const context=await browser.newContext({...devices['iPhone 13'],acceptDownloads:true});
 const page=await context.newPage();const errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 page.on('dialog',d=>d.accept());
 await page.goto('http://127.0.0.1:8876/');
 const state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('setter-stats-game')));
 const totals=async(s,a)=>{const g=await state();assert.equal(g.totalSets,s);assert.equal(g.assistCount,a);assert.equal(await page.locator('#totalSets').textContent(),String(s));assert.equal(await page.locator('#assistCount').textContent(),String(a));};
 const set=page.locator('[data-set-event="set"]'),assist=page.locator('[data-set-event="assist"]');
 assert.equal(await page.locator('[data-set-event]').count(),2);
 assert.equal(await page.locator('[data-assist]').count(),0);
 await set.tap();await totals(0,0);
 await set.dblclick();await totals(1,0);
 await assist.tap();await totals(1,0);
 await assist.dblclick();await totals(2,1);
 await page.locator('#back').click();await totals(2,1);
 await page.locator('#back').dblclick();await totals(1,0);
 await assist.dblclick();await totals(2,1);
 await page.locator('[data-stat="digs"][data-change="1"]').click();assert.equal((await state()).digs,0);
 await page.locator('[data-stat="digs"][data-change="1"]').dblclick();assert.equal((await state()).digs,1);
 await page.locator('[data-ace]').dblclick();assert.equal((await state()).serves,1);
 await page.locator('#opponent').fill('Browser Test');
 await page.locator('#set-plus').click();assert.equal((await state()).savedSets.length,0);
 await page.locator('#set-plus').dblclick();await totals(0,0);
 assert.equal((await state()).savedSets[0].totalSets,2);assert.equal((await state()).savedSets[0].assistCount,1);
 await page.reload();assert.equal((await state()).savedSets.length,1);
 await page.locator('#viewSaved').click();assert.equal(await page.locator('#entryView').isVisible(),true);
 await page.locator('#viewSaved').dblclick();
 assert.match(await page.locator('#savedSetsList').innerText(),/Total Sets 2/);
 assert.match(await page.locator('#savedSetsList').innerText(),/Assists 1/);
 const downloadPromise=page.waitForEvent('download');await page.locator('#exportExcelSaved').dblclick();
 const download=await downloadPromise;assert.equal(download.suggestedFilename(),'Lauren_browser-test_setter-stats.xls');
 const exportPath='/home/jeremy/.cache/setter-sets-assists-test.xls';await download.saveAs(exportPath);const content=fs.readFileSync(exportPath,'utf8');
 assert.match(content,/<th>Total Sets<\/th><th>Assists<\/th>/);
 assert.match(content,/TOTALS \(All Sets\)/);assert.ok(!content.includes('Front Set'));
 await page.locator('#savedBack').dblclick();
 await page.locator('#viewDiagram').dblclick();assert.equal(await page.locator('#barval-totalSets').textContent(),'2');assert.equal(await page.locator('#barval-assistCount').textContent(),'1');
 await page.locator('#diagramBack').dblclick();
 await assist.dblclick();await totals(1,1);
 const box1=await set.boundingBox(),box2=await assist.boundingBox();assert.equal(box1.y,box2.y);assert.ok(box1.height>=44 && box2.height>=44);
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:'/home/jeremy/.cache/setter-sets-assists-mobile.png',fullPage:true});
 await set.locator('..').locator('..').locator('..').screenshot({path:'/home/jeremy/.cache/setter-sets-assists-panel.png'});
 await page.locator('#reset').click();await totals(1,1);
 await page.locator('#reset').dblclick();await totals(0,0);assert.equal((await state()).savedSets.length,0);
 await page.evaluate(()=>navigator.serviceWorker.ready);
 await page.reload();await context.setOffline(true);await page.reload();assert.equal(await page.locator('[data-set-event]').count(),2);await assist.dblclick();await totals(1,1);
 assert.deepEqual(errors,[]);
 console.log('PASS '+(process.env.ENGINE||'chromium')+': mobile controls, single/double taps, undo, unrelated stats, save/reload/review/chart/export, reset, offline, layout; no page errors');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
