// Reset clears new counters, retained legacy buckets, and saved sets.
const assert=require('node:assert/strict');
const path=require('node:path');
const {runHarness}=require('./harness');
const h=runHarness(path.join(__dirname,'..','index.html'),{assists:{'front-perfectKill':2},attacks:3});
h.getEl('set-plus').ondblclick();
h.action({setEvent:'assist'});
h.action({setEvent:'set'});
assert.equal(h.readGame().totalSets,2);
assert.equal(h.readGame().assistCount,1);
assert.equal(h.readGame().savedSets.length,1);
h.clickReset();
const g=h.readGame();
assert.equal(g.totalSets,0);assert.equal(g.assistCount,0);
assert.ok(Object.values(g.assists).every(v=>v===0));
assert.equal(g.savedSets.length,0);
assert.equal(g.attacks,0);assert.equal(g.serves,0);assert.equal(g.setNumber,1);
assert.equal(h.getEl('totalSets').textContent,'0');
assert.equal(h.getEl('assistCount').textContent,'0');
console.log('PASS reset clears new and legacy stats, saved sets and rendered totals');
