const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {runHarness}=require('./harness');
const file=path.join(__dirname,'..','index.html');
const legacy={opponent:'Test',setNumber:2,assists:{'front-perfect':3,'front-perfectKill':2,'back-decentKill':1},savedSets:[{setNumber:1,assists:{'middle-perfect':4,'middle-perfectKill':2}}]};
const h=runHarness(file,legacy);
assert.equal(h.readGame().totalSets,6,'all legacy entries count as sets');
assert.equal(h.readGame().assistCount,3,'only legacy Kill entries count as assists');
assert.equal(h.readGame().savedSets[0].totalSets,6);
assert.equal(h.readGame().savedSets[0].assistCount,2);
assert.equal(h.readGame().assists['front-perfect'],3,'raw legacy buckets retained');
assert.deepEqual(runHarness(file,h.readGame()).readGame(),h.readGame(),'migration idempotent');
h.action({setEvent:'assist'});
h.getEl('set-plus').ondblclick();
assert.equal(h.readGame().savedSets[1].totalSets,7);
assert.equal(h.readGame().savedSets[1].assistCount,4);
assert.equal(h.readGame().totalSets,0);
assert.equal(h.readGame().assistCount,0);
assert.equal(h.getEl('barval-totalSets').textContent,'13');
assert.equal(h.getEl('barval-assistCount').textContent,'6');
h.getEl('viewSaved').ondblclick();
assert.match(h.getEl('savedSetsList').innerHTML,/Total Sets <strong>7<\/strong>/);
assert.match(h.getEl('savedSetsList').innerHTML,/Assists <strong>4<\/strong>/);
const html=fs.readFileSync(file,'utf8');
assert.match(html,/data-set-event="set"/);
assert.match(html,/data-set-event="assist"/);
assert.ok(!html.includes('ASSIST QUALITY BY SET LOCATION'));
assert.ok(!html.includes('ASSISTS BY LOCATION &amp; QUALITY'));
assert.match(html,/\['Total Sets','totalSets'\]/);
assert.match(html,/\['Assists','assistCount'\]/);
h.clickReset();
assert.equal(h.readGame().totalSets,0);
assert.equal(h.readGame().assistCount,0);
assert.equal(h.readGame().savedSets.length,0);
console.log('PASS legacy migration, persistence, save/advance, charts, review, reset and UI/export schema');
